# Generated by Django 5.1.7 on 2025-03-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='tempo_consulta',
            field=models.IntegerField(),
        ),
    ]
