# Generated by Django 5.1.7 on 2025-03-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_medico_tempo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='atendimento',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medico',
            name='convenio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medico',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medico',
            name='experiencia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medico',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='patologias',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medico',
            name='residencia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medico',
            name='retorno',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medico',
            name='video',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculdade_nome', models.CharField(max_length=255)),
                ('curso_nome', models.CharField(max_length=255)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to='medicos.medico')),
            ],
        ),
    ]
