# Generated by Django 5.1.7 on 2025-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_medico_atendimento_medico_convenio_medico_crm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
