# Generated by Django 5.1.7 on 2025-03-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_remove_medico_facebook_remove_medico_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacao',
            name='data_conclusao',
        ),
        migrations.AddField(
            model_name='medico',
            name='stars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='medico',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
