# Generated by Django 5.1.7 on 2025-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_remove_formacao_data_conclusao_medico_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto_fundo',
            field=models.ImageField(default='', upload_to='fundos_medicos/'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(default='', upload_to='fotos_medicos/'),
        ),
    ]
