services:
  - type: web
    name: kayadoc
    env: python
    buildCommand: |
      cd theme/static_src
      npm install
      npm run build
      cd ../../
      pip install -r requirements.txt
      python manage.py tailwind build
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn kayadoc.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DJANGO_SETTINGS_MODULE
        value: kayadoc.settings
      - key: DEBUG
        value: "False"
